# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-SanitizeUrl
version:      0.2.0
version_from: lib/Catalyst/Plugin/SanitizeUrl.pm
installdirs:  site
requires:
    Catalyst:                      5.23

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
